spring.application.name=TelegramBot

bot.name=notdupelbot
bot.token=8549480952:AAEa5FwUmHwGvniFLs-UPRmvTjA6wl6oFns
admin.id=793164386


spring.datasource.url=jdbc:postgresql://localhost:5432/tgbot_database
spring.datasource.username=postgres
spring.datasource.password=QWER2404ty

# ????????? ??? ??????????????? ???????? ?????? ? ?????? ?????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
