spring.application.name=TelegramBot

bot.token=${BOT_TOKEN}
spring.datasource.password=${DB_PASSWORD}

bot.name=notdupelbot

admin.id=7096046399


spring.datasource.url=jdbc:postgresql://localhost:5432/tgbot_database
spring.datasource.username=postgres


# ????????? ??? ??????????????? ???????? ?????? ? ?????? ?????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
