package com.bot.TelegramBot.AdminComponents;

public enum AdminState {

    FREE,
    LESSON_WAITING_FOR_LINK,
    LESSON_WAITING_FOR_NAME,
    LESSON_WAITING_FOR_SELECTIVE,
    LESSON_WAITING_FOR_TEACHER,
    SCHITEM_WAITING_FOR_DAY,
    SCHITEM_WAITING_FOR_LESSON_AUDITORY,
    SCHITEM_WAITING_FOR_LESSON_NAME,
    SCHITEM_WAITING_FOR_LESSON_NUMBER,
    STUDENT_WAITING_FOR_INVITE_CODE,
    STUDENT_WAITING_FOR_NAME,
    STUDENT_WAITING_FOR_SUBJECTS,
    STUDENT_WAITING_FOR_SURNAME,
    EDIT_SUBJECT_WAITING_FOR_ID,
    EDIT_SUBJECT_NAME,
    EDIT_SUBJECT_TEACHER,
    EDIT_SUBJECT_LINK,
    EDIT_SUBJECT_SELECTIVE,
    BROADCAST_WAITING_FOR_MESSAGE

}
