package com.bot.TelegramBot.AdminComponents;

public enum AdminState {

    FREE,
    WAITING_FOR_STUDENT_NAME,
    WAITING_FOR_STUDENT_SURNAME,
    WAITING_FOR_STUDENT_INVITE_CODE,
    WAITING_FOR_STUDENT_SUBJECTS,
    WAITING_FOR_LESSON_NAME,
    WAITING_FOR_LESSON_LINK,
    WAITING_FOR_LESSON_TEACHER,
    WAITING_FOR_LESSON_SELECTIVE,
    WAITING_FOR_SCHITEM_DAY,
    WAITING_FOR_SCHITEM_LESSON_NUMBER,
    WAITING_FOR_SCHITEM_LESSON_NAME,
    WAITING_FOR_SCHITEM_LESSON_AUDITORY,;
}
